// <auto-generated />
using EmployeeManagementAPI.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace EmployeeManagementAPI.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("EmployeeManagementAPI.Models.Employee", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Department")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EmployeeType")
                        .IsRequired()
                        .HasMaxLength(13)
                        .HasColumnType("nvarchar(13)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Employees");

                    b.HasDiscriminator<string>("EmployeeType").HasValue("Employee");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("EmployeeManagementAPI.Models.Contractor", b =>
                {
                    b.HasBaseType("EmployeeManagementAPI.Models.Employee");

                    b.HasDiscriminator().HasValue("Contractor");
                });

            modelBuilder.Entity("EmployeeManagementAPI.Models.Finance", b =>
                {
                    b.HasBaseType("EmployeeManagementAPI.Models.Employee");

                    b.HasDiscriminator().HasValue("Finance");
                });

            modelBuilder.Entity("EmployeeManagementAPI.Models.HR", b =>
                {
                    b.HasBaseType("EmployeeManagementAPI.Models.Employee");

                    b.HasDiscriminator().HasValue("HR");
                });

            modelBuilder.Entity("EmployeeManagementAPI.Models.Manager", b =>
                {
                    b.HasBaseType("EmployeeManagementAPI.Models.Employee");

                    b.HasDiscriminator().HasValue("Manager");
                });

            modelBuilder.Entity("EmployeeManagementAPI.Models.Permanent", b =>
                {
                    b.HasBaseType("EmployeeManagementAPI.Models.Employee");

                    b.HasDiscriminator().HasValue("Permanent");
                });
#pragma warning restore 612, 618
        }
    }
}
