name: Build and Deploy to AKS via ACR
on:
  push:
    branches:
      - main

permissions:
  id-token: write  # Required for OIDC login, but won't be needed in this case if using client secret

jobs:
  build-and-deploy:
    runs-on: windows-latest 

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Azure Login action
        uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
          enable-AzPSSession: true

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Cache Docker layers
        uses: actions/cache@v2
        with:
          path: ~/.cache/docker
          key: ${{ runner.os }}-docker-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-docker-

      - name: Build Docker image
        run: |
          docker build -t anilmacr.azurecr.io/employeemanagementapi:${{ github.sha }} .

      - name: Log in to Azure Container Registry (ACR)
        run: |
          az acr login --name anilmacr

      - name: Push Docker image to ACR
        run: |
          docker push anilmacr.azurecr.io/employeemanagementapi:${{ github.sha }}

      - name: Configure kubectl to access AKS
        run: |
          az aks get-credentials --resource-group anilm-rg --name anilm-kub

      - name: Deploy to AKS
        run: |
          kubectl set image deployment/employeemanagementapi employeemanagementapi=anilmacr.azurecr.io/employeemanagementapi:${{ github.sha }}
          kubectl rollout status deployment/employeemanagementapi
