name: Build and Deploy to AKS via ACR
on:
  push:
    branches:
      - main

permissions:
  id-token: write  # Required for OIDC login, but won't be needed in this case if using client secret

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest 

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Azure Login action
        uses: azure/login@v2
        with:
          creds: '{"clientId":"9e9df261-0f96-4ca7-b907-6fda24df3f6b","clientSecret":"TQd8Q~pF1uccGC~MfrihxO-.FvVnR6jRyeSK8akf","subscriptionId":"342c1e10-cb97-423b-888f-9b72b4a6dd41","tenantId":"0797c077-647a-43b9-b582-bb3ffc77cc57"}'

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Cache Docker layers
        uses: actions/cache@v2
        with:
          path: ~/.cache/docker
          key: ${{ runner.os }}-docker-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-docker-

      - name: Build Docker image
        run: |
          docker build -t anilmacr.azurecr.io/employeemanagementapi:${{ github.sha }} .

      - name: Log in to Azure Container Registry (ACR)
        run: |
          az acr login --name anilmacr

      - name: Push Docker image to ACR
        run: |
          docker push anilmacr.azurecr.io/employeemanagementapi:${{ github.sha }}

      - name: Configure kubectl to access AKS
        run: |
          az aks get-credentials --resource-group anilm-rg --name anilm-kub

      - name: Deploy to AKS
        run: |
          kubectl set image deployment/employeemanagementapi employeemanagementapi=anilmacr.azurecr.io/employeemanagementapi:${{ github.sha }}
          kubectl rollout status deployment/employeemanagementapi
